<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Perform predictionUse a trained model t_a88417</name>
   <tag></tag>
   <elementGuidId>063cd1f3-dd3f-4349-a6c7-fe1cae17f623</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div/div/div/section/div/div[3]/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9ec2e928-e625-4d2e-8a6e-13ef0db97a83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Perform predictionUse a trained model to make a prediction or estimate about the outcome of a particular input or set of inputs.</value>
      <webElementGuid>12bfbf4d-a370-4be3-a137-f8ac5db9f3f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;ant-spin-nested-loading&quot;]/div[@class=&quot;ant-spin-container&quot;]/div[@class=&quot;ant-spin-nested-loading&quot;]/div[@class=&quot;ant-spin-container&quot;]/div[@class=&quot;Datacontent&quot;]/div[@class=&quot;bg-back&quot;]/section[@class=&quot;p-0&quot;]/div[@class=&quot;csvupload_page&quot;]/div[@class=&quot;mt-4 p-0 select-experiment-type mx-auto&quot;]/div[@class=&quot;h-55vh overflow-auto bg-grey-o&quot;]/div[@class=&quot;radio-text-container&quot;]/div[1]</value>
      <webElementGuid>bf7bd76d-9878-4e20-a1c1-7ad5eb05aa3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/div/section/div/div[3]/div/div[2]/div</value>
      <webElementGuid>3beca255-00fe-4f27-ab6b-8e1da0291349</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data designer'])[1]/following::div[2]</value>
      <webElementGuid>a74761b8-b632-4970-a4a1-12f61eecd218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Instance segmentation'])[1]/preceding::div[1]</value>
      <webElementGuid>d3e35d5b-5ad9-4c6a-a71b-f55da2ba848d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div</value>
      <webElementGuid>4bb7c8be-8dad-4dcf-914d-0cc1cc65d304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Perform predictionUse a trained model to make a prediction or estimate about the outcome of a particular input or set of inputs.' or . = 'Perform predictionUse a trained model to make a prediction or estimate about the outcome of a particular input or set of inputs.')]</value>
      <webElementGuid>a20c6b7b-de3b-4623-a9b5-75d705ce26eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
