<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Loading results_float-right down-arrow</name>
   <tag></tag>
   <elementGuidId>6cf77690-f8e8-4351-81d7-7b8144f9ade4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div/div/div/section/div[2]/div/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.float-right.down-arrow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c220e472-1be8-41f4-b2aa-8d44aa3618d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/chevron-right.e684cb98f4103b0520a1f3d15bdcacf2.svg</value>
      <webElementGuid>5e12f9b3-a9cc-435d-bf86-52cd44f61f21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>info</value>
      <webElementGuid>d13782ec-781a-44e2-8370-d4ad08fc545c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>float-right down-arrow</value>
      <webElementGuid>507100aa-33e9-40fa-9707-f5b2920d2182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;ant-spin-nested-loading&quot;]/div[@class=&quot;ant-spin-container&quot;]/div[@class=&quot;ant-spin-nested-loading&quot;]/div[@class=&quot;ant-spin-container&quot;]/div[@class=&quot;Datacontent&quot;]/div[@class=&quot;bg-back&quot;]/section[@class=&quot;p-0&quot;]/div[@class=&quot;progress-loader float-right&quot;]/div[@class=&quot;loading-header text-white pt-3 pb-2 px-3 bg-gray-o&quot;]/span[1]/img[@class=&quot;float-right down-arrow&quot;]</value>
      <webElementGuid>997941ef-3e51-413a-aa1f-8c189cf717ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/div/section/div[2]/div/span/img</value>
      <webElementGuid>7bd1ae89-6b07-4872-a5f0-a916d0d02126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='info']</value>
      <webElementGuid>0217b695-8527-41a1-81fe-b8d338f1e941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/img</value>
      <webElementGuid>13b2f71e-8201-48b3-aede-f91822d92f96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/media/chevron-right.e684cb98f4103b0520a1f3d15bdcacf2.svg' and @alt = 'info']</value>
      <webElementGuid>37e3fdbf-3f0e-4f36-ba3d-fd5ac6dc526f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
