<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Loading results_float-right</name>
   <tag></tag>
   <elementGuidId>41c9427e-df7f-4e6d-91d0-11e78fbcbfd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div/div/div/section/div[2]/div/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.float-right</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d930d64c-6e0c-4bd3-be9b-0370ea9d36c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/close-icon.e20279ac4433a2ac04225d21f9064a29.svg</value>
      <webElementGuid>ba1b8314-4cd8-48c1-acaa-12421ee3e84e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>info</value>
      <webElementGuid>45b93cc3-4458-45dc-afc2-eae4e97ea310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>float-right</value>
      <webElementGuid>74e1e572-1961-4c35-ad47-a88bc6d062bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;ant-spin-nested-loading&quot;]/div[@class=&quot;ant-spin-container&quot;]/div[@class=&quot;ant-spin-nested-loading&quot;]/div[@class=&quot;ant-spin-container&quot;]/div[@class=&quot;Datacontent&quot;]/div[@class=&quot;bg-back&quot;]/section[@class=&quot;p-0&quot;]/div[@class=&quot;progress-loader float-right&quot;]/div[@class=&quot;loading-header text-white pt-3 pb-2 px-3 bg-gray-o&quot;]/span[1]/img[@class=&quot;float-right&quot;]</value>
      <webElementGuid>cccd73e6-0235-406e-85de-53e94783c364</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/div/section/div[2]/div/span/img</value>
      <webElementGuid>fa929d86-2c63-4f37-b71a-de95c81ea0e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='info']</value>
      <webElementGuid>474239b0-ab45-4fcc-967a-e4f53fc4da93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/img</value>
      <webElementGuid>3982055b-cfe7-4f30-9001-b3ccd3b50806</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/media/close-icon.e20279ac4433a2ac04225d21f9064a29.svg' and @alt = 'info']</value>
      <webElementGuid>837fb4db-e589-4997-b67c-21c45b50921e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
