<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email id_email</name>
   <tag></tag>
   <elementGuidId>d8711e68-e5a0-406f-995f-5dd57b69d059</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#InputEmail1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='InputEmail1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6583925d-2650-4a06-954e-ac3bdda43b99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>314f5afa-d59d-4829-b94c-40aa8bf88857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2c955edc-7671-498d-a205-3ee5030b5eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InputEmail1</value>
      <webElementGuid>ef49a414-6e6e-444b-80a8-2d30b597c462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describeby</name>
      <type>Main</type>
      <value>emailHelp</value>
      <webElementGuid>07d60877-cb28-4737-bf8d-2733c13ad134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter email</value>
      <webElementGuid>bc687705-0778-4614-a637-ea40d19d9c5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>5c204a59-4c1d-482e-8975-6e13339c9a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InputEmail1&quot;)</value>
      <webElementGuid>53aaa3ae-8d34-44a1-a38d-4202fac23553</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='InputEmail1']</value>
      <webElementGuid>15d6d49e-45c8-4053-8f11-1d3a15bca9bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/div/section/div[2]/section/section/form/div/input</value>
      <webElementGuid>6dbff96a-f685-4a65-baad-75e1facbd739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>99db90b5-6df7-4463-be63-940ce02a27f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'InputEmail1' and @placeholder = 'Enter email' and @name = 'email']</value>
      <webElementGuid>a96ba9fc-8217-4e61-be90-8b27fb9e3c6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
