<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Data prediction analysisThis experiment_480949</name>
   <tag></tag>
   <elementGuidId>064483ec-3b9f-4153-bf4a-f6a4a341b455</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.custom-control.custom-radio</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div/div/section/div/div[2]/div[2]/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a809b80a-6398-4ab5-a33a-d64ce775c36d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-control custom-radio</value>
      <webElementGuid>81d4f5a6-5e76-4f9a-938f-b1b1b6d6932c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Data prediction analysisThis experiment type will help to predict results from a large datasets.</value>
      <webElementGuid>3062c2c4-fd49-4a9a-b047-8c0f6a0f11ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;ant-spin-nested-loading&quot;]/div[@class=&quot;ant-spin-container&quot;]/div[@class=&quot;ant-spin-nested-loading&quot;]/div[@class=&quot;ant-spin-container&quot;]/div[@class=&quot;Datacontent&quot;]/section[@class=&quot;p-0&quot;]/div[@class=&quot;csvupload_page&quot;]/div[@class=&quot;row px-0 predictor-section&quot;]/div[@class=&quot;col-md-8 bg-gray-a ml-2 summarypredictor-type px-0&quot;]/div[@class=&quot;experiment-main position-relative&quot;]/div[@class=&quot;primary-predictorform&quot;]/div[@class=&quot;form-radio&quot;]/div[@class=&quot;custom-control custom-radio&quot;]</value>
      <webElementGuid>b1938cdc-995c-4f86-85ac-64aeeac492bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/section/div/div[2]/div[2]/div/div[2]/div/div</value>
      <webElementGuid>c8b6263e-349d-40cd-81db-370ed2330c86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Experiment Type'])[1]/following::div[3]</value>
      <webElementGuid>0b85b092-ee1e-4c9a-ab3e-30d682701dfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm &amp; Run'])[1]/following::div[6]</value>
      <webElementGuid>26a48ed8-067d-4ad9-9306-706049fc0622</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::div[1]</value>
      <webElementGuid>99a4906a-a1b6-45fa-bec1-519e9f79405b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div</value>
      <webElementGuid>15c41e6b-c06e-4d92-9834-a00ba62032b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Data prediction analysisThis experiment type will help to predict results from a large datasets.' or . = 'Data prediction analysisThis experiment type will help to predict results from a large datasets.')]</value>
      <webElementGuid>fc079c70-b742-49c9-92e7-17e3d6f89bb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
