<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_New upload_img-fluid</name>
   <tag></tag>
   <elementGuidId>9d9eee67-3fa1-4e21-829f-23b5dc703f2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.image_upload.mb-0 > img.img-fluid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div/div/div/div/div/form/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a798ec80-6eb4-481f-885f-7bf92680b877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid</value>
      <webElementGuid>a0c8d55c-f35a-4439-a6aa-3dfb84b3cd49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAB4AAAAeCAYAAAA7MK6iAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAEvSURBVHgB7ZZRasMwDEClyPkYbIF+FlrYbrKbLDdLchPvJHMhY5+D0I9CInvJOidm1K2hTfORPAiWkW0RWZIFZcWm//bNG/xRVk3q6sDhs+Js0DWZq/Od958IJmIyw4IgSu3kUB/erUxMEgjSU5s060KQkJ3ccLNzdb7zFrCLXjupuZYvqwfVyV/f5pmJX2EkRGu7T4c4jtN2UJ18NIoZjMQM02mTEIYsDF3n4xhLw9XN0NXlnvvfN0YX26dYwh0QoIeyiBFKuBPTubp1cG4npjY7GAlC+mDD+cWF5xqBWzDHdHLdGJl08ygKuILQa1l6rhF7JJQEmPeG1wledafhaLVOhviZsnKF4fZmLoaN2q58D0tX+7X6lRCVe0awYV//hQR5O8iTWyKd2/RcGoEfvyKv7+NOfe0AAAAASUVORK5CYII=</value>
      <webElementGuid>75dce40d-e459-4310-8243-9a89eac2602a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;ant-spin-nested-loading&quot;]/div[@class=&quot;ant-spin-container&quot;]/div[@class=&quot;ant-spin-nested-loading&quot;]/div[@class=&quot;ant-spin-container&quot;]/div[@class=&quot;Datacontent&quot;]/div[@class=&quot;csvupload_page&quot;]/div[@class=&quot;upload_content&quot;]/div[@class=&quot;uploaddata&quot;]/form[@class=&quot;form-container upload_tag&quot;]/div[@class=&quot;fileupload_section&quot;]/div[@class=&quot;image_upload mb-0&quot;]/img[@class=&quot;img-fluid&quot;]</value>
      <webElementGuid>2417300a-6276-4ef6-b92c-44f6d2c4c9fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/div/div/div/form/div/div/img</value>
      <webElementGuid>84e9b4a1-da94-470e-b0c6-2f9f3e2293f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAB4AAAAeCAYAAAA7MK6iAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAEvSURBVHgB7ZZRasMwDEClyPkYbIF+FlrYbrKbLDdLchPvJHMhY5+D0I9CInvJOidm1K2hTfORPAiWkW0RWZIFZcWm//bNG/xRVk3q6sDhs+Js0DWZq/Od958IJmIyw4IgSu3kUB/erUxMEgjSU5s060KQkJ3ccLNzdb7zFrCLXjupuZYvqwfVyV/f5pmJX2EkRGu7T4c4jtN2UJ18NIoZjMQM02mTEIYsDF3n4xhLw9XN0NXlnvvfN0YX26dYwh0QoIeyiBFKuBPTubp1cG4npjY7GAlC+mDD+cWF5xqBWzDHdHLdGJl08ygKuILQa1l6rhF7JJQEmPeG1wledafhaLVOhviZsnKF4fZmLoaN2q58D0tX+7X6lRCVe0awYV//hQR5O8iTWyKd2/RcGoEfvyKv7+NOfe0AAAAASUVORK5CYII=')]</value>
      <webElementGuid>9f4b4778-c031-453f-b796-8792078c2601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/img</value>
      <webElementGuid>5e43e5cf-3a70-4ee7-8d0b-0da34814aca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAB4AAAAeCAYAAAA7MK6iAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAEvSURBVHgB7ZZRasMwDEClyPkYbIF+FlrYbrKbLDdLchPvJHMhY5+D0I9CInvJOidm1K2hTfORPAiWkW0RWZIFZcWm//bNG/xRVk3q6sDhs+Js0DWZq/Od958IJmIyw4IgSu3kUB/erUxMEgjSU5s060KQkJ3ccLNzdb7zFrCLXjupuZYvqwfVyV/f5pmJX2EkRGu7T4c4jtN2UJ18NIoZjMQM02mTEIYsDF3n4xhLw9XN0NXlnvvfN0YX26dYwh0QoIeyiBFKuBPTubp1cG4npjY7GAlC+mDD+cWF5xqBWzDHdHLdGJl08ygKuILQa1l6rhF7JJQEmPeG1wledafhaLVOhviZsnKF4fZmLoaN2q58D0tX+7X6lRCVe0awYV//hQR5O8iTWyKd2/RcGoEfvyKv7+NOfe0AAAAASUVORK5CYII=']</value>
      <webElementGuid>f7443b02-03fe-4c45-9b7f-5d492adaa5a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
