<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email id_email</name>
   <tag></tag>
   <elementGuidId>40761ac9-9d1c-4689-b457-dbf7e7aca5f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#InputEmail1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='InputEmail1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9def0865-bf64-460d-b160-854995dac9a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>fcffeb81-a9f7-45a1-ae9e-43bc763fee9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>75bfc270-4e2c-4716-ab61-567905747daf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InputEmail1</value>
      <webElementGuid>451ffdf3-4bad-4d9f-9733-5a56a4ec6120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describeby</name>
      <type>Main</type>
      <value>emailHelp</value>
      <webElementGuid>820d69ab-4bdf-4afc-961c-86f1f595903f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter email</value>
      <webElementGuid>1c5ce286-d58b-4da2-9815-2e0a3917720d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>3819df8e-51e1-46d8-83c7-b5624c5e92bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InputEmail1&quot;)</value>
      <webElementGuid>2d1dfda5-7998-4302-a7a0-6f474bbde9da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='InputEmail1']</value>
      <webElementGuid>1c4dd214-336a-441c-b856-9e83cf5563a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/div/section/div[2]/section/section/form/div/input</value>
      <webElementGuid>6f78c9fb-a053-400c-a3cb-340cbcfa107d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8fb3f940-0b98-4a58-a24c-fb5f991ae853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'InputEmail1' and @placeholder = 'Enter email' and @name = 'email']</value>
      <webElementGuid>72142ed3-7cfd-49d5-b14b-c4c9ccf38016</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
