<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Categorial0</name>
   <tag></tag>
   <elementGuidId>84e57851-b87d-4c9a-8ff1-de3bfebb8435</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.list-group.pb-5 > div.list-group-item.list-group-item-action.flex-column.align-items-start.bg-transparent.border-0.px-0 > div.text-white</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div/div/div/section/div[2]/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>93e2269d-8adf-4075-a2fa-e56a2be4f4cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-white</value>
      <webElementGuid>95373f54-3eee-4bee-921b-75d47083b363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Categorial0</value>
      <webElementGuid>a19779b4-babf-4d00-bee2-f879b6eea7a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;ant-spin-nested-loading&quot;]/div[@class=&quot;ant-spin-container&quot;]/div[@class=&quot;ant-spin-nested-loading&quot;]/div[@class=&quot;ant-spin-container&quot;]/div[@class=&quot;Datacontent&quot;]/div[@class=&quot;bg-back&quot;]/section[@class=&quot;p-0&quot;]/div[@class=&quot;row pl-5 pr-4 m-0 summary-page-height&quot;]/div[@class=&quot;col-md-2 bg-gray-a br10 basic-detail-column&quot;]/div[@class=&quot;list-group pb-5&quot;]/div[@class=&quot;list-group-item list-group-item-action flex-column align-items-start 
bg-transparent border-0 px-0&quot;]/div[@class=&quot;text-white&quot;]</value>
      <webElementGuid>f19399e7-8c6f-4687-ad8f-565af057ac0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/div/section/div[2]/div/div[2]/div/div</value>
      <webElementGuid>808bd84b-7f91-453e-a867-719e8fd78661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dataset column details'])[1]/following::div[2]</value>
      <webElementGuid>1a91f287-29ba-4be7-a477-5861be6c76cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dataset records'])[1]/following::div[3]</value>
      <webElementGuid>2dd47e4b-92ab-458e-9f6f-3a051af9402b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Numeric'])[1]/preceding::div[1]</value>
      <webElementGuid>adea3ff0-52a7-4065-865d-6274d517b3a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div</value>
      <webElementGuid>6b503bf7-eecb-44a3-b0ba-46fc62d51370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Categorial0' or . = 'Categorial0')]</value>
      <webElementGuid>20da9acb-38f1-4311-b6c2-d119d78f3f57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
