<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email id_email</name>
   <tag></tag>
   <elementGuidId>551b996f-534d-4e12-a839-f03edb95d69e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#InputEmail1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='InputEmail1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>395e4b2c-dd04-4710-92d0-0810f22bed98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>69ae85af-5e4f-44e8-8f85-1856aa320383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>57013ed6-6f01-4a42-b54f-3a7bfeab92ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InputEmail1</value>
      <webElementGuid>8a64cf02-6716-44fc-b301-72e275b7ff6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describeby</name>
      <type>Main</type>
      <value>emailHelp</value>
      <webElementGuid>3822aa34-7c65-46dd-9b08-4a0fc7cbe6ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter email</value>
      <webElementGuid>754c6637-dfd7-41a9-82f7-1da6aa4172b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>63f0ebc0-6915-471d-be64-2aa4dda0b057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InputEmail1&quot;)</value>
      <webElementGuid>f210c4f9-db59-49dd-92cd-7c3d8e7ccf82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='InputEmail1']</value>
      <webElementGuid>4b292eb7-ede4-4c4c-bf09-92852e2a342e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/div/section/div[2]/section/section/form/div/input</value>
      <webElementGuid>16f6c1f4-ab7f-4bda-9025-8d2a5a85cfc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>13dcb4bf-c52f-44da-8809-bfbaac824c46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'InputEmail1' and @placeholder = 'Enter email' and @name = 'email']</value>
      <webElementGuid>529137cc-10c2-4788-b4ab-ec32e27d4758</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
