<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Single datasetSingle dataset will be used here</name>
   <tag></tag>
   <elementGuidId>367a83f0-cef3-4399-88ac-23acbca9a046</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.list-group-item.px-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul/li[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>2d9ac94f-0faf-42f8-9e6c-b829d9ec0898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-group-item px-0</value>
      <webElementGuid>c5c98b3e-3e51-4ee6-8b52-9d1ecc6da628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Single datasetSingle dataset will be used here</value>
      <webElementGuid>0e3cc949-8c12-4d47-866f-336a2e339ce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;ant-spin-nested-loading&quot;]/div[@class=&quot;ant-spin-container&quot;]/div[@class=&quot;ant-spin-nested-loading&quot;]/div[@class=&quot;ant-spin-container&quot;]/div[@class=&quot;Datacontent&quot;]/div[@class=&quot;csvupload_page&quot;]/div[@class=&quot;upload_content upload-dataset&quot;]/div[@class=&quot;uploaddata p-4&quot;]/ul[@class=&quot;list-group list-group-horizontal-md mb-2 no-border-color&quot;]/li[@class=&quot;list-group-item px-0&quot;]</value>
      <webElementGuid>dbdfb9a4-8943-4d14-adfe-92d9c3e03bb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/div/div/div/ul/li[2]</value>
      <webElementGuid>98316444-b08b-46a0-bca4-ae009346f40f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Do you want to upload single or multiple dataset?'])[1]/following::li[2]</value>
      <webElementGuid>692c86a2-f22d-49bd-91b2-0228f90e36e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload dataset module'])[1]/following::li[2]</value>
      <webElementGuid>d8ec1da1-c7d3-401b-9348-dc7e3b9397aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Multiple dataset'])[1]/preceding::li[3]</value>
      <webElementGuid>d1a0ea5b-05e2-4fde-95ed-46477dcd8059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/li[2]</value>
      <webElementGuid>3bf62811-d747-47b9-9b68-1c4b4bc7e2dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = ' Single datasetSingle dataset will be used here' or . = ' Single datasetSingle dataset will be used here')]</value>
      <webElementGuid>61d8c9e4-6faa-4c3a-9426-134f521ab4f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
